version: '3.8'

services:
  your-api:
    working_dir: /app
    image: bentmelis/tripplannerbackend:latest
    ports:
      - "8080:80"
    environment:
     ASPNETCORE_ENVIRONMENT: Production
     MYSQL_DB_USERNAME: root
     MYSQL_DB_PASSWORD: abc123
     DB_SERVER: mysql-trips
     MYSQL_DB_PORT: 3304
     DB_NAME: Tripplanner
    restart: always
  mysql-trips:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_trips_data:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: abc123
volumes:
 mysql_trips_data: