version: '3.8'

services:
  your-api:
    depends_on:
      - mysql-trips
    working_dir: /app
    image: bentmelis/tripplannerbackend:latest
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_SERVER: ${DB_SERVER}
      DB_NAME: ${DB_NAME}
    restart: always
  mysql-trips:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_trips_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
volumes:
 mysql_trips_data: {}
