version: '3.8'

services:
  your-api:
    depends_on:
      - mysql-trips
    working_dir: /app
    image: bentmelis/tripplannerbackend:latest
    ports:
      - "80:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SERVER: ${{ secrets.DB_SERVER }}
      DB_NAME: ${{ secrets.DB_TABLE }}
    restart: always
  mysql-trips:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_trips_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
volumes:
 mysql_trips_data: {}