version: '3.8'

services:
  your-api:
    depends_on:
      - mysql-trips
    working_dir: /app
    image: bentmelis/tripplannerbackend:latest
    ports:
      - "80:6587"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_USER: root
      DB_PASSWORD: abc123
      DB_SERVER: mysql-trips
      DB_NAME: TripPlanner
      DB_PORT: 3306
    restart: always
  mysql-trips:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - mysql_trips_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123
volumes:
 mysql_trips_data: {}